name: ChristineHavens
favicon: null
layout_spectrum: 0.49316
typography_spectrum: 0.25214
title: Christine Havens
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#113355'
    - '#fefefe'
    - '#000000'
    - '#aaaaaa'
    - '#808080'
  brandStrength: 0.24374151905067265
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.37311373837292194
purpose: []
